import { LayoutThemeConfig } from "@/Theme/config";
import "./globals.css";

export const metadata = {
  title: "Next App + Material UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutThemeConfig>
          {children}
        </LayoutThemeConfig>
      </body>
    </html>
  );
}
